FROM openjdk:11
COPY src/CovidTrackerAppApplication-0.0.1-SNAPSHOT.jar CovidTrackerAppApplication-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/CovidTrackerAppApplication-0.0.1-SNAPSHOT.jar"]
